# Generated by Django 6.0.3 on 2026-03-08 05:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('sensor_offline', 'Sensor Offline'), ('high_acceleration', 'High Acceleration'), ('frequency_shift', 'Frequency Shift Detected'), ('drift_exceeded', 'Drift Threshold Exceeded'), ('system_error', 'System Error')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DriftMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measurement_time', models.DateTimeField(db_index=True)),
                ('displacement_x', models.FloatField()),
                ('displacement_y', models.FloatField()),
                ('total_displacement', models.FloatField()),
                ('inter_story_drift_ratio', models.FloatField(help_text='Displacement / Story Height')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DriftSafetyThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_inter_story_drift_ratio', models.FloatField(help_text='Maximum allowable drift ratio (e.g., 0.02 for 2%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('building_code', models.CharField(default='NSCP 2010', help_text='e.g., NSCP 2010, IBC 2021', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ETABSBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g., Building Model v1.0', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('earthquake', 'Earthquake'), ('blast', 'Blast/Explosion'), ('footfall', 'Footfall/Impact'), ('wind', 'Wind-Induced'), ('traffic', 'Traffic-Induced'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('peak_acceleration', models.FloatField(help_text='Peak acceleration magnitude during event')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FFTAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_date', models.DateTimeField()),
                ('frequency_range_min', models.FloatField(help_text='Min frequency analyzed (Hz)')),
                ('frequency_range_max', models.FloatField(help_text='Max frequency analyzed (Hz)')),
                ('primary_frequency', models.FloatField(help_text='Dominant frequency found (Hz)')),
                ('primary_amplitude', models.FloatField()),
                ('analysis_notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FloorLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField(help_text='e.g., 1, 2, 3 or -1 for basement')),
                ('floor_name', models.CharField(help_text="e.g., 'Ground Floor', 'Level 3'", max_length=100)),
                ('height_above_ground', models.FloatField(help_text='Height in meters above ground')),
            ],
            options={
                'ordering': ['floor_number'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sensor_type', models.CharField(choices=[('raspberry_shake', 'Raspberry Shake 4D'), ('accelerometer', 'Accelerometer'), ('seismometer', 'Seismometer'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(help_text='Building location/floor', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('installation_date', models.DateTimeField()),
                ('last_reading', models.DateTimeField(blank=True, null=True)),
                ('calibration_factor', models.FloatField(default=1.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_name', models.CharField(choices=[('shm', 'SHM'), ('nfd', 'NFD'), ('drift', 'Drift')], max_length=50, unique=True)),
                ('sampling_rate', models.IntegerField(default=50, help_text='Hz')),
                ('measurement_units', models.CharField(choices=[('metric', 'Metric (m, m/s², Hz)'), ('imperial', 'Imperial (ft, g, Hz)')], default='metric', max_length=50)),
                ('alert_email', models.CharField(blank=True, help_text='Send alerts to this email', max_length=255)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('last_calibrated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='DriftAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_status', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical'), ('cleared', 'Cleared')], default='warning', max_length=20)),
                ('exceeded_by_percent', models.FloatField(help_text='How much threshold was exceeded (%)')),
                ('alert_triggered_time', models.DateTimeField(auto_now_add=True)),
                ('resolved_time', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.driftmeasurement')),
                ('threshold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.driftsafetythreshold')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='driftmeasurement',
            name='event_related',
            field=models.ForeignKey(blank=True, help_text='Link to seismic/event trigger if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.event'),
        ),
        migrations.AddField(
            model_name='driftsafetythreshold',
            name='lower_floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_thresholds', to='core.floorlevel'),
        ),
        migrations.AddField(
            model_name='driftsafetythreshold',
            name='upper_floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_thresholds_upper', to='core.floorlevel'),
        ),
        migrations.AddField(
            model_name='driftmeasurement',
            name='lower_floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_lower', to='core.floorlevel'),
        ),
        migrations.AddField(
            model_name='driftmeasurement',
            name='upper_floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_upper', to='core.floorlevel'),
        ),
        migrations.CreateModel(
            name='NaturalFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode_number', models.IntegerField(help_text='e.g., 1st mode, 2nd mode')),
                ('frequency_hz', models.FloatField(help_text='Frequency in Hertz')),
                ('frequency_source', models.CharField(choices=[('analytical', 'Analytical (ETABS)'), ('experimental', 'Experimental (FFT)')], default='experimental', max_length=50)),
                ('damping_ratio', models.FloatField(help_text='Damping ratio (0-1 or percentage)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('last_measured', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('baseline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frequencies', to='core.etabsbaseline')),
            ],
            options={
                'ordering': ['mode_number'],
            },
        ),
        migrations.CreateModel(
            name='FrequencyComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency_diff', models.FloatField(help_text='Difference in Hz (can be negative)')),
                ('frequency_diff_percent', models.FloatField(help_text='Percentage difference')),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('degraded', 'Degraded'), ('alert', 'Alert')], default='normal', max_length=50)),
                ('assessment', models.TextField(blank=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fftanalysis')),
                ('baseline_frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='core.naturalfrequency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fftanalysis',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fft_analyses', to='core.sensor'),
        ),
        migrations.AddField(
            model_name='event',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.sensor'),
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('acceleration_x', models.FloatField()),
                ('acceleration_y', models.FloatField()),
                ('acceleration_z', models.FloatField()),
                ('magnitude', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.sensor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='driftsafetythreshold',
            unique_together={('lower_floor', 'upper_floor')},
        ),
        migrations.CreateModel(
            name='SHMTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique_for_month=True)),
                ('avg_acceleration', models.FloatField()),
                ('max_acceleration', models.FloatField()),
                ('min_acceleration', models.FloatField()),
                ('event_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='core.sensor')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('sensor', 'date')},
            },
        ),
    ]
