# Generated by Django 5.2.12 on 2026-03-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFDResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dominant_frequency', models.FloatField()),
                ('damping_ratio', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='Normal', max_length=20)),
            ],
        ),
    ]
