# Generated by Django 5.2.12 on 2026-03-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_nfdresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfdresult',
            name='fft_amplitudes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfdresult',
            name='fft_frequencies',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
