# Generated by Django 5.2.12 on 2026-03-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_nfdresult_fft_amplitudes_nfdresult_fft_frequencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfdresult',
            name='etabs_frequency',
            field=models.FloatField(default=2.941),
        ),
        migrations.AddField(
            model_name='nfdresult',
            name='frequency_difference',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfdresult',
            name='frequency_difference_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nfdresult',
            name='fft_amplitudes',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nfdresult',
            name='fft_frequencies',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
