# Generated by Django 5.2.12 on 2026-03-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_nfdresult_etabs_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFDHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dominant_frequency', models.FloatField()),
                ('damping_ratio', models.FloatField()),
                ('matched_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('etabs_frequency', models.FloatField(blank=True, null=True)),
                ('frequency_difference_percent', models.FloatField(blank=True, null=True)),
                ('classification', models.CharField(default='Ambient', max_length=50)),
                ('status', models.CharField(default='Normal', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='nfdresult',
            name='fft_amplitudes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='nfdresult',
            name='fft_frequencies',
            field=models.JSONField(default=list),
        ),
    ]
