# Generated by Django 5.2.12 on 2026-03-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_nfdhistory_alter_nfdresult_fft_amplitudes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfdresult',
            name='peak_acceleration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
