# Generated by Django 5.2.12 on 2026-03-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_nfdresult_peak_acceleration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SHMHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('peak_frequency', models.FloatField()),
                ('peak_acceleration', models.FloatField()),
                ('baseline_frequency', models.FloatField(blank=True, null=True)),
                ('frequency_difference_percent', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
