# Generated by Django 5.2.12 on 2026-03-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_shmhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SHMHistory',
        ),
        migrations.AddField(
            model_name='nfdhistory',
            name='peak_acceleration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
