# Generated by Django 5.2.12 on 2026-03-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_shmhistory_nfdhistory_peak_acceleration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SHMHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('peak_frequency', models.FloatField()),
                ('baseline_frequency', models.FloatField(blank=True, null=True)),
                ('residual', models.FloatField(blank=True, null=True)),
                ('stiffness', models.FloatField(blank=True, null=True)),
                ('drift_assessment', models.CharField(max_length=50)),
                ('structural_condition', models.CharField(max_length=50)),
                ('peak_acceleration', models.FloatField(blank=True, null=True)),
                ('classification', models.CharField(default='Ambient', max_length=50)),
                ('status', models.CharField(default='Normal', max_length=20)),
            ],
        ),
    ]
