# Generated by Django 5.2.12 on 2026-03-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_shmhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriftHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('f1_mdr', models.FloatField(default=0)),
                ('f2_mdr', models.FloatField(default=0)),
                ('f3_mdr', models.FloatField(default=0)),
                ('f1_diff', models.FloatField(default=0)),
                ('f2_diff', models.FloatField(default=0)),
                ('f3_diff', models.FloatField(default=0)),
                ('overall_status', models.CharField(default='Normal', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='nfdresult',
            name='etabs_frequency',
            field=models.FloatField(default=5.671),
        ),
    ]
