# Generated by Django 5.2.12 on 2026-03-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_drifthistory_alter_nfdresult_etabs_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='drifthistory',
            name='f1_acc_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drifthistory',
            name='f1_acc_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drifthistory',
            name='f1_base_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drifthistory',
            name='f1_base_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drifthistory',
            name='f1_drift_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drifthistory',
            name='f1_drift_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drifthistory',
            name='f2_acc_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drifthistory',
            name='f2_acc_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drifthistory',
            name='f2_base_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drifthistory',
            name='f2_base_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drifthistory',
            name='f2_drift_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drifthistory',
            name='f2_drift_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drifthistory',
            name='f3_acc_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drifthistory',
            name='f3_acc_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drifthistory',
            name='f3_base_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drifthistory',
            name='f3_base_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drifthistory',
            name='f3_drift_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drifthistory',
            name='f3_drift_y',
            field=models.FloatField(default=0),
        ),
    ]
